jwt 기능 간단 구현
nooose/ddd pull request #18
Opened 2024-10-29 02:29 UTC by nonoro

- jwt 를 이용한 사용자 인증 구현

2024-10-29 06:23 UTC, nooose requested changes

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/test/kotlin/wolfdesk/base/filter/jwt/JwtFilterTest.kt
> +        every { request.getSession(false) } returns null
모킹없이 `MockHttpServletRequest`으로 테스트할 수 있음

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/security/SecurityConfig.kt
> +    }
companion object는 클래스 제일 아래에 배치하는 것이 컨벤션임

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/security/SecurityConfig.kt
> +            httpBasic { }
이건 왜 함?

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        }
null이 아닐 때 early return으로 변경하기

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +            )
UsernamePasswordAuthenticationToken 대신 AbstractAuthenticationToken 상속받아 인증토큰객체 직접 만들어보기
그리고 커스텀 로그인을 만들어야 하기 때문에 UserDetailsService를 사용할 이유는 없어보임

2024-10-29 06:23 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        }
OncePerRequestFilter 에서 shouldNotFilter 함수를 제공하고 있음, 요거를 오버라이드해서 사용하면됨

2024-10-30 07:48 UTC, nonoro commented on wolfdesk/modules/base/src/test/kotlin/wolfdesk/base/filter/jwt/JwtFilterTest.kt
> +        every { request.getSession(false) } returns null
MockHttpServletRequest, MockHttpServletResponse로 바꿔서 해놈 확인점

2024-10-30 07:48 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/security/SecurityConfig.kt
> +    }
수정완료

2024-10-30 07:49 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/security/SecurityConfig.kt
> +            httpBasic { }
모름 ... 지워버림

2024-10-30 08:03 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        }
변경하였읍미다

2024-10-30 18:13 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +            )
만들었음 ㅎㅎ

2024-10-30 18:19 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        }
완료~!

2024-10-31 01:52 UTC, nooose requested changes

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/CustomAuthenticationToken.kt
> +    private val principal: Any,
인증주체를 나중에 꺼내서 쓰게될텐데 Any 타입이면 매번 형변환필요할 수 있음

이것도 하나 만들어서 사용하는 게 좋아보임

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/CustomAuthenticationToken.kt
> +    private val credentials: Any? = null,
credentials 필요하지 않으니 인스턴스 변수로 가지고 있을필요는 없어보임

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        if (shouldNotFilter(request)) {
shouldNotFilter 오버라이드만 해주면 어차피 상위 콜스택에서 호출하기 때문에
추가로 실행할 이유없음

shouldNotFilter에서 걸리면 `doFilterInternal`를 호출하지 않음 OncePerRequestFilter 들어가서 확인ㄱㄱ

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
이건 뭐하는거?

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        return request.requestURI in SecurityConfig.PERMITALL_URIS
`PERMIT_ALL_URIS` 이렇게 바꾸는게 좋지않겠음?

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        if (isTokenInvalid(token)) {
isInvalidToken이 더 자연스러워보임

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +            return
이렇게 처리하지말고 예외를 던지게 만들고 AuthenticationEntryPoint 같은것을 만들어서 등록하는것이 좋음

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        authentication.details = WebAuthenticationDetailsSource().buildDetails(request)
이거 꼭 해야함? 궁금해서 질문임

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        if (isTokenInvalid(token)) {
따라가면 token.isNullOrBlank() 사용하는 것 같은데 
이정도면 isInvalidToken 함수를 사용하지 않아도될것같음

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
>          }
인증토큰을 시큐리티홀더에 넣어주고 다음 필터를 호출해야함
그래야 정상적인 필터체인이 연결됨

그래서 필터에서 return 하면 정상적인 동작이 되지않음

2024-10-31 01:52 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
>          }
Stateless 정책이기 때문에 매요청마다 인증을 새로해야함
그러므로 JwtFilter에서 SecurityContextHolder.getContext().authentication을 까보면 항상 null임

JwtFilter가 하는 일은 Jwt 토큰을 얻어 인증객체를 만들고 시큐리티홀더에 담아주는 역할을 해야함

2024-10-31 05:02 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
인증객체 만들어서 넣어주는거

2024-10-31 05:02 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        return request.requestURI in SecurityConfig.PERMITALL_URIS
ㅇㅋㅇㅋ

2024-10-31 05:03 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        authentication.details = WebAuthenticationDetailsSource().buildDetails(request)
모름 나도 다들 이렇게하길래 이렇게함 ...

2024-10-31 05:03 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
>          }
그거 저 아래서 하는데 그럼 저 리턴을 걍 없애? 어짜피 실행안되려나?

2024-10-31 05:19 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/CustomAuthenticationToken.kt
> +    private val principal: Any,
ㅇㅋㄷㅋ

2024-10-31 05:51 UTC, nooose commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
>          }
불필요한거같음
JWT 추출불가능하면 인증되지 않은 Authentication을 넘기면 좋을 거같음

2024-10-31 06:02 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/CustomAuthenticationToken.kt
> +    private val credentials: Any? = null,
제거하고 오버라이드한 함수에서 null 리턴하도록 변경함

2024-10-31 06:02 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        if (shouldNotFilter(request)) {
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/96f354e3-7ab8-4dee-81d8-db6ca109aa70">
확인

2024-10-31 06:05 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
> +        if (isTokenInvalid(token)) {
변경완료

2024-10-31 07:45 UTC, nonoro commented on wolfdesk/modules/base/src/main/kotlin/wolfdesk/base/filter/jwt/JwtFilter.kt
>          }
이거 이쪽 로직 오기전에 jwt 추출불가능하면 그냥 예외로 날려버려서 그냥 저부분 없애고 저기 들어온 순간 무조건 jwt 인증 됐다고 보고 인증객체 만들어서 넣고 다음 필터로 넘기는걸로 했음!

2024-11-10 08:23 UTC, nooose requested changes

2024-11-10 10:12 UTC, merged